services:

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ldps_network


  mqtt_service:
    build: .
    container_name: mqtt_service
    env_file:
      - .env
    command: ["poetry", "run", "python", "-m", "local_data_process_service.app"]
    depends_on:
      - redis
    networks:
      - ldps_network


  celery_worker:
    build: .
    container_name: celery_worker
    env_file:
      - .env
    command: ["poetry", "run", "celery", "-A", "local_data_process_service.capp", "worker", "--loglevel=info"]
    depends_on:
      - redis
    networks:
      - ldps_network
  
  
networks:
  ldps_network:
    driver: bridge