openapi: "3.0.0"
info:
  title: "Smart Farm API"
  description: "A simple Flask-RESTful API with Swagger UI"
  version: "1.0.0"

paths:
  /api/v1/tests:
    get:
      summary: "Get a test API"
      description: "An initial test API"
      tags:
        - Test
      responses:
        200:
          description: "A 'Hello World!' string"

  /api/v1/auth/github:
    post:
      summary: "GitHub Login"
      description: "Login endpoint that validates user credentials and returns an access token."
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firebase_jwt:
                  type: string
                  example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
      responses:
        200:
          description: "Successful login, returns JWT token"
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."