# Generated by Django 5.1.7 on 2025-03-31 19:25

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='plant_image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_image_of', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', '-timestamp'],
            },
        ),
    ]
