services:
  mqtt-kafka-bridge:
    build:
      context: .
      dockerfile: Dockerfile
    image: mqtt-kafka-bridge:latest
    container_name: mqtt-kafka-bridge
    env_file: .env
    networks:
      - smart-farm

networks:
  smart-farm:
    driver: bridge