spring:
  kafka:
    bootstrap-servers: localhost:9092

    streams:
      application-id: threshold-validation

      properties:
        broker: localhost:9092
        data-topic: sensor-data
        threshold-topic: threshold-config
        alerts-topic: alert

    consumer:
      key-deserializer:
        org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: 
        org.apache.kafka.common.serialization.StringDeserializer