spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}

    streams:
      application-id: threshold-validation

      properties:
        broker: ${KAFKA_BOOTSTRAP_SERVER}
        data-topic: sensor-data
        threshold-topic: threshold-config
        alerts-topic: alert
        sasl:
          mechanism: ${KAFKA_SASL_MECHANISM}
          jaas:
            config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
        security:
          protocol: ${KAFKA_SECURITY_PROTOCOL}

    consumer:
      key-deserializer:
        org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: 
        org.apache.kafka.common.serialization.StringDeserializer