spring:
  application:
    name: kafka-stream-test


  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    consumer:
      group-id: ${KAFKA_GROUP_ID}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        sasl:
          mechanism: ${KAFKA_SASL_MECHANISM}
          jaas:
            config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
        security:
          protocol: ${KAFKA_SECURITY_PROTOCOL}
  

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME}
    password: ${GOOGLE_APP}
    protocol: smtp
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com


logging:
  level:
    root: "INFO"