name: hcmut-smart-farm-microservices

services:
  mqtt-kafka-bridge:
    build:
      context: ./mqtt-kafka-bridge
      dockerfile: Dockerfile
    image: mqtt-kafka-bridge:latest
    container_name: mqtt-kafka-bridge
    env_file: ./mqtt-kafka-bridge/.env
    networks:
      - hcmut-smart-farm


  threshold-validation:
    build:
      context: ./threshold-validation
      dockerfile: Dockerfile
    image: threshold-validation:latest
    env_file:
      - ./threshold-validation/.env
    container_name: threshold-validation
    networks:
      - hcmut-smart-farm

  tsdb-writer:
    build:
      context: ./tsdb-writer
      dockerfile: Dockerfile
    image: tsdb-writer:latest
    container_name: tsdb-writer
    env_file: ./tsdb-writer/.env
    networks:
      - hcmut-smart-farm


  realtime-service:
    build:
      context: ./realtime-service
      dockerfile: Dockerfile
    image: realtime-service
    container_name: realtime-service
    env_file: ./realtime-service/.env
    networks:
      - hcmut-smart-farm
    ports:
      - 8080:8080
    expose:
      - 8080


networks:
  hcmut-smart-farm:
    driver: bridge